gsap.registerPlugin(ScrollTrigger);
const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
function intro(){if(reduce){gsap.set(".loader",{display:"none"});return}const t=gsap.timeline();t.to(".loader-line",{width:"100%",duration:1.1,ease:"power2.inOut"}).from(".loader p",{y:35,opacity:0,filter:"blur(10px)",duration:.8},"<.15").from(".loader span",{opacity:0,y:8,duration:.5},"<.25").to(".loader",{yPercent:-100,duration:1,ease:"power4.inOut",delay:.25}).set(".loader",{display:"none"}).from(".hero-copy>*",{y:28,opacity:0,stagger:.1,duration:.8,ease:"power3.out"},"-=.45")}
function lenis(){if(reduce)return null;const l=new Lenis({duration:1.1,smoothWheel:true});l.on("scroll",ScrollTrigger.update);gsap.ticker.add(t=>l.raf(t*1000));gsap.ticker.lagSmoothing(0);return l}
function motion(){if(reduce)return;gsap.to(".hero-media",{yPercent:18,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});gsap.to(".hero-copy",{yPercent:28,opacity:.15,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});
const mm=gsap.matchMedia();mm.add("(min-width: 801px)",()=>{const frame=document.querySelector(".scale-frame");gsap.timeline({scrollTrigger:{trigger:".scale-stage",start:"top top",end:"bottom bottom",scrub:1,pin:frame,pinSpacing:false}}).to(frame,{x:"-22.5vw",width:"100vw",height:"100vh",ease:"none"});const track=document.querySelector(".h-track");const horiz=gsap.to(track,{x:()=>-(track.scrollWidth-innerWidth),ease:"none",scrollTrigger:{trigger:".horizontal",start:"top top",end:()=>"+="+(track.scrollWidth-innerWidth),pin:true,scrub:1,invalidateOnRefresh:true}});return()=>horiz.kill()});
gsap.from(".statement h2",{y:70,opacity:0,scrollTrigger:{trigger:".statement",start:"top 70%",end:"top 30%",scrub:1}});gsap.to(".art-break img",{scale:1.12,yPercent:5,ease:"none",scrollTrigger:{trigger:".art-break",start:"top bottom",end:"bottom top",scrub:true}})}
function menu(){const b=document.querySelector(".menu-btn"),n=document.querySelector(".mobile-nav"),c=document.querySelector(".nav-close");b.onclick=()=>n.classList.add("open");c.onclick=()=>n.classList.remove("open");n.querySelectorAll("a").forEach(a=>a.onclick=()=>n.classList.remove("open"))}
function pointer(){if(reduce||!matchMedia("(hover:hover) and (pointer:fine)").matches)return;const hero=document.querySelector(".hero");hero.addEventListener("pointermove",e=>{const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*8;gsap.to(".hero-media",{x,y,duration:1.2,ease:"power3.out",overwrite:"auto"})});hero.addEventListener("pointerleave",()=>gsap.to(".hero-media",{x:0,y:0,duration:1}))}
intro();lenis();motion();menu();pointer();window.addEventListener("load",()=>ScrollTrigger.refresh());